package com.nhat.tidal_terror.client;
// Generated by tools/create_reef_equipment_models.py; native bake is the UV source of truth.
import com.nhat.tidal_terror.TidalTerror;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;

public final class ReefArmorModel extends HumanoidModel<net.minecraft.client.renderer.entity.state.HumanoidRenderState> {
    public ReefArmorModel(ModelPart root) { super(root); }
    public static ModelLayerLocation layer(EquipmentSlot slot) {
        return new ModelLayerLocation(Identifier.fromNamespaceAndPath(TidalTerror.MODID, "reef_armor"), slot.getName());
    }
    public static LayerDefinition createLayer(EquipmentSlot slot) {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.ZERO);
        root.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.ZERO);
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.ZERO);
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create(), PartPose.offset(-5,2,0));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create(), PartPose.offset(5,2,0));
        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create(), PartPose.offset(-1.9F,12,0));
        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create(), PartPose.offset(1.9F,12,0));
        if (slot == EquipmentSlot.HEAD) {
        head.addOrReplaceChild("violet_0", CubeListBuilder.create().texOffs(0,0).addBox(-5.00F,-8.00F,-5.00F,10.00F,2.00F,10.00F, new CubeDeformation(0.002F)), PartPose.ZERO);
        head.addOrReplaceChild("violet_1", CubeListBuilder.create().texOffs(41,0).addBox(-4.00F,-10.00F,-4.00F,8.00F,2.00F,8.00F, new CubeDeformation(0.003F)), PartPose.ZERO);
        head.addOrReplaceChild("violet_2", CubeListBuilder.create().texOffs(74,0).addBox(-3.00F,-11.00F,-3.00F,6.00F,1.00F,6.00F, new CubeDeformation(0.004F)), PartPose.ZERO);
        head.addOrReplaceChild("violet_3", CubeListBuilder.create().texOffs(99,0).addBox(-5.00F,-6.00F,2.00F,10.00F,6.00F,3.00F, new CubeDeformation(0.005F)), PartPose.ZERO);
        head.addOrReplaceChild("ivory_4", CubeListBuilder.create().texOffs(126,0).addBox(-5.00F,-6.00F,-4.00F,1.00F,6.00F,6.00F, new CubeDeformation(0.006F)), PartPose.ZERO);
        head.addOrReplaceChild("violet_5", CubeListBuilder.create().texOffs(141,0).addBox(-5.00F,-7.00F,-5.00F,1.00F,3.00F,7.00F, new CubeDeformation(0.007F)), PartPose.ZERO);
        head.addOrReplaceChild("ivory_6", CubeListBuilder.create().texOffs(158,0).addBox(4.00F,-6.00F,-4.00F,1.00F,6.00F,6.00F, new CubeDeformation(0.008F)), PartPose.ZERO);
        head.addOrReplaceChild("violet_7", CubeListBuilder.create().texOffs(173,0).addBox(4.00F,-7.00F,-5.00F,1.00F,3.00F,7.00F, new CubeDeformation(0.009F)), PartPose.ZERO);
        head.addOrReplaceChild("cobalt_8", CubeListBuilder.create().texOffs(190,0).addBox(3.00F,-10.00F,0.00F,2.00F,3.00F,3.00F, new CubeDeformation(0.010F)), PartPose.ZERO);
        head.addOrReplaceChild("cobalt_9", CubeListBuilder.create().texOffs(201,0).addBox(4.00F,-8.00F,2.00F,2.00F,3.00F,3.00F, new CubeDeformation(0.011F)), PartPose.ZERO);
        }
        if (slot == EquipmentSlot.CHEST) {
        body.addOrReplaceChild("ivory_10", CubeListBuilder.create().texOffs(212,0).addBox(-4.00F,1.00F,-4.00F,8.00F,10.00F,2.00F, new CubeDeformation(0.012F)), PartPose.ZERO);
        body.addOrReplaceChild("violet_11", CubeListBuilder.create().texOffs(233,0).addBox(-4.00F,2.00F,-5.00F,8.00F,7.00F,2.00F, new CubeDeformation(0.013F)), PartPose.ZERO);
        body.addOrReplaceChild("violet_12", CubeListBuilder.create().texOffs(0,13).addBox(-3.00F,9.00F,-5.00F,6.00F,1.00F,2.00F, new CubeDeformation(0.014F)), PartPose.ZERO);
        body.addOrReplaceChild("ivory_13", CubeListBuilder.create().texOffs(17,13).addBox(-4.00F,1.00F,2.00F,8.00F,10.00F,2.00F, new CubeDeformation(0.015F)), PartPose.ZERO);
        body.addOrReplaceChild("violet_14", CubeListBuilder.create().texOffs(38,13).addBox(-4.00F,2.00F,3.00F,8.00F,7.00F,2.00F, new CubeDeformation(0.016F)), PartPose.ZERO);
        body.addOrReplaceChild("violet_15", CubeListBuilder.create().texOffs(59,13).addBox(-3.00F,9.00F,3.00F,6.00F,1.00F,2.00F, new CubeDeformation(0.017F)), PartPose.ZERO);
        body.addOrReplaceChild("ivory_16", CubeListBuilder.create().texOffs(76,13).addBox(-5.00F,1.00F,-2.00F,1.00F,10.00F,4.00F, new CubeDeformation(0.018F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("ivory_17", CubeListBuilder.create().texOffs(87,13).addBox(-4.00F,-2.00F,-3.00F,6.00F,3.00F,6.00F, new CubeDeformation(0.019F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("violet_18", CubeListBuilder.create().texOffs(112,13).addBox(-4.00F,-3.00F,-3.00F,6.00F,2.00F,6.00F, new CubeDeformation(0.020F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("violet_19", CubeListBuilder.create().texOffs(137,13).addBox(-3.00F,-4.00F,-2.00F,4.00F,1.00F,4.00F, new CubeDeformation(0.021F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("ivory_20", CubeListBuilder.create().texOffs(154,13).addBox(-3.00F,5.00F,-3.00F,4.00F,3.00F,6.00F, new CubeDeformation(0.022F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("violet_21", CubeListBuilder.create().texOffs(175,13).addBox(-3.00F,5.00F,-4.00F,4.00F,2.00F,2.00F, new CubeDeformation(0.023F)), PartPose.ZERO);
        rightArm.addOrReplaceChild("slate_22", CubeListBuilder.create().texOffs(188,13).addBox(-3.00F,8.00F,-2.00F,4.00F,1.00F,4.00F, new CubeDeformation(0.024F)), PartPose.ZERO);
        body.addOrReplaceChild("ivory_23", CubeListBuilder.create().texOffs(205,13).addBox(4.00F,1.00F,-2.00F,1.00F,10.00F,4.00F, new CubeDeformation(0.025F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("ivory_24", CubeListBuilder.create().texOffs(216,13).addBox(-2.00F,-2.00F,-3.00F,6.00F,3.00F,6.00F, new CubeDeformation(0.026F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("violet_25", CubeListBuilder.create().texOffs(0,28).addBox(-2.00F,-3.00F,-3.00F,6.00F,2.00F,6.00F, new CubeDeformation(0.027F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("violet_26", CubeListBuilder.create().texOffs(25,28).addBox(-1.00F,-4.00F,-2.00F,4.00F,1.00F,4.00F, new CubeDeformation(0.028F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("ivory_27", CubeListBuilder.create().texOffs(42,28).addBox(-1.00F,5.00F,-3.00F,4.00F,3.00F,6.00F, new CubeDeformation(0.029F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("violet_28", CubeListBuilder.create().texOffs(63,28).addBox(-1.00F,5.00F,-4.00F,4.00F,2.00F,2.00F, new CubeDeformation(0.030F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("slate_29", CubeListBuilder.create().texOffs(76,28).addBox(-1.00F,8.00F,-2.00F,4.00F,1.00F,4.00F, new CubeDeformation(0.031F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("violet_30", CubeListBuilder.create().texOffs(93,28).addBox(-2.00F,-3.00F,-4.00F,6.00F,3.00F,1.00F, new CubeDeformation(0.032F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("cobalt_31", CubeListBuilder.create().texOffs(108,28).addBox(1.00F,-5.00F,-2.00F,2.00F,3.00F,3.00F, new CubeDeformation(0.033F)), PartPose.ZERO);
        leftArm.addOrReplaceChild("cobalt_32", CubeListBuilder.create().texOffs(119,28).addBox(2.00F,-3.00F,1.00F,2.00F,2.00F,3.00F, new CubeDeformation(0.034F)), PartPose.ZERO);
        body.addOrReplaceChild("cobalt_33", CubeListBuilder.create().texOffs(130,28).addBox(-3.00F,1.00F,5.00F,2.00F,3.00F,2.00F, new CubeDeformation(0.035F)), PartPose.ZERO);
        body.addOrReplaceChild("cobalt_34", CubeListBuilder.create().texOffs(139,28).addBox(-2.00F,4.00F,5.00F,2.00F,3.00F,2.00F, new CubeDeformation(0.036F)), PartPose.ZERO);
        }
        if (slot == EquipmentSlot.LEGS) {
        body.addOrReplaceChild("ivory_35", CubeListBuilder.create().texOffs(148,28).addBox(-4.00F,10.00F,-3.00F,8.00F,2.00F,6.00F, new CubeDeformation(0.037F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("ivory_36", CubeListBuilder.create().texOffs(177,28).addBox(-2.50F,0.00F,-3.00F,5.00F,5.00F,6.00F, new CubeDeformation(0.038F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("violet_37", CubeListBuilder.create().texOffs(200,28).addBox(-2.50F,1.00F,-4.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.039F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("violet_38", CubeListBuilder.create().texOffs(215,28).addBox(-2.50F,1.00F,2.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.040F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("slate_39", CubeListBuilder.create().texOffs(230,28).addBox(-2.50F,5.00F,-2.50F,5.00F,1.00F,5.00F, new CubeDeformation(0.041F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("ivory_40", CubeListBuilder.create().texOffs(0,40).addBox(-2.50F,0.00F,-3.00F,5.00F,5.00F,6.00F, new CubeDeformation(0.042F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("violet_41", CubeListBuilder.create().texOffs(23,40).addBox(-2.50F,1.00F,-4.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.043F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("violet_42", CubeListBuilder.create().texOffs(38,40).addBox(-2.50F,1.00F,2.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.044F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("slate_43", CubeListBuilder.create().texOffs(53,40).addBox(-2.50F,5.00F,-2.50F,5.00F,1.00F,5.00F, new CubeDeformation(0.045F)), PartPose.ZERO);
        }
        if (slot == EquipmentSlot.FEET) {
        leftLeg.addOrReplaceChild("ivory_44", CubeListBuilder.create().texOffs(74,40).addBox(-2.50F,6.00F,-3.00F,5.00F,5.00F,6.00F, new CubeDeformation(0.046F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("violet_45", CubeListBuilder.create().texOffs(97,40).addBox(-2.50F,7.00F,-4.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.047F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("slate_46", CubeListBuilder.create().texOffs(112,40).addBox(-2.50F,10.00F,-3.00F,5.00F,1.00F,6.00F, new CubeDeformation(0.048F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("ivory_47", CubeListBuilder.create().texOffs(135,40).addBox(-2.50F,11.00F,-4.00F,5.00F,2.00F,7.00F, new CubeDeformation(0.049F)), PartPose.ZERO);
        leftLeg.addOrReplaceChild("slate_48", CubeListBuilder.create().texOffs(160,40).addBox(-1.50F,11.00F,-5.00F,3.00F,2.00F,1.00F, new CubeDeformation(0.050F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("ivory_49", CubeListBuilder.create().texOffs(169,40).addBox(-2.50F,6.00F,-3.00F,5.00F,5.00F,6.00F, new CubeDeformation(0.051F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("violet_50", CubeListBuilder.create().texOffs(192,40).addBox(-2.50F,7.00F,-4.00F,5.00F,3.00F,2.00F, new CubeDeformation(0.052F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("slate_51", CubeListBuilder.create().texOffs(207,40).addBox(-2.50F,10.00F,-3.00F,5.00F,1.00F,6.00F, new CubeDeformation(0.053F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("ivory_52", CubeListBuilder.create().texOffs(230,40).addBox(-2.50F,11.00F,-4.00F,5.00F,2.00F,7.00F, new CubeDeformation(0.054F)), PartPose.ZERO);
        rightLeg.addOrReplaceChild("slate_53", CubeListBuilder.create().texOffs(0,52).addBox(-1.50F,11.00F,-5.00F,3.00F,2.00F,1.00F, new CubeDeformation(0.055F)), PartPose.ZERO);
        }
        return LayerDefinition.create(mesh, 256, 256);
    }
}
