architectury { common 'fabric', 'neoforge' }
loom { mixin { defaultRefmapName = 'tidalterror-1.21.1-refmap.json' } }
dependencies {
    implementation project(':common')
    modImplementation "net.fabricmc:fabric-loader:${project.loader}"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabricApi}"
    modImplementation "dev.architectury:architectury:${project.api}"
    modImplementation 'com.github.glitchfiend:TerraBlender-fabric:1.21.1-4.1.0.8'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}
processResources {
    from(rootProject.file('src/main/resources')) { include 'assets/**', 'tidalterror-icon.png' }
}

sourceSets.main.java.srcDir rootProject.file('common-versioned/src/main/java')
sourceSets.main.java.srcDir rootProject.file('common-1201-1211/src/main/java')

jar { from project(':common').sourceSets.main.output; duplicatesStrategy = DuplicatesStrategy.EXCLUDE }

sourceSets.main.java.srcDir rootProject.file('common-modern/src/main/java')

sourceSets.main.java.srcDir rootProject.file('common-universal/src/main/java')

sourceSets.main.java.srcDir rootProject.file('common-ports/src/main/java')
