package com.nhat.tidal_terror.client;
// Generated by tools/create_reef_equipment_models.py.
import com.nhat.tidal_terror.TidalTerror;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;

public final class ReefSpearModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"reef_spear"), "main");
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("coral_0", CubeListBuilder.create().texOffs(0,0).addBox(-0.50F,-12.00F,-0.50F,1.00F,36.00F,1.00F, new CubeDeformation(0.002F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_1", CubeListBuilder.create().texOffs(5,0).addBox(-1.00F,-13.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.003F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_2", CubeListBuilder.create().texOffs(14,0).addBox(-1.00F,-10.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.004F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_3", CubeListBuilder.create().texOffs(23,0).addBox(-1.00F,0.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.005F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_4", CubeListBuilder.create().texOffs(32,0).addBox(-1.00F,2.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.006F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_5", CubeListBuilder.create().texOffs(41,0).addBox(-1.00F,18.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.007F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_6", CubeListBuilder.create().texOffs(50,0).addBox(-1.00F,22.00F,-1.00F,2.00F,1.00F,2.00F, new CubeDeformation(0.008F)), PartPose.ZERO);
        root.addOrReplaceChild("hide_7", CubeListBuilder.create().texOffs(59,0).addBox(-1.50F,-14.00F,-1.00F,3.00F,2.00F,2.00F, new CubeDeformation(0.009F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_8", CubeListBuilder.create().texOffs(70,0).addBox(-2.00F,-18.00F,-0.50F,4.00F,4.00F,1.00F, new CubeDeformation(0.010F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_9", CubeListBuilder.create().texOffs(81,0).addBox(-1.50F,-21.00F,-0.50F,3.00F,3.00F,1.00F, new CubeDeformation(0.011F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_10", CubeListBuilder.create().texOffs(90,0).addBox(-1.00F,-24.00F,-0.50F,2.00F,3.00F,1.00F, new CubeDeformation(0.012F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_11", CubeListBuilder.create().texOffs(97,0).addBox(-0.50F,-26.00F,-0.50F,1.00F,2.00F,1.00F, new CubeDeformation(0.013F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_12", CubeListBuilder.create().texOffs(102,0).addBox(-2.50F,-17.00F,-0.50F,5.00F,1.00F,1.00F, new CubeDeformation(0.014F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_13", CubeListBuilder.create().texOffs(115,0).addBox(-2.00F,-19.00F,-0.50F,4.00F,1.00F,1.00F, new CubeDeformation(0.015F)), PartPose.ZERO);
        root.addOrReplaceChild("tooth_14", CubeListBuilder.create().texOffs(126,0).addBox(-1.50F,-22.00F,-0.50F,3.00F,1.00F,1.00F, new CubeDeformation(0.016F)), PartPose.ZERO);
        return LayerDefinition.create(mesh,256,256);
    }
    private ReefSpearModel() {}
}
