"""Construct Veilglow's hollow stepped bell, bloom core and six ribbon chains."""
from pathlib import Path
import math,json
ROOT=Path(__file__).resolve().parents[1]
parts={'body':('root',(0,0,0),0),'bell':('body',(0,-5,0),0),'rim':('body',(0,-5,0),0),'core':('body',(0,-8,0),0)}
boxes=[]
def box(part,x,y,z,w,h,d):boxes.append(dict(part=part,x=x,y=y,z=z,w=w,h=h,d=d))
# Hollow sides, rather than a solid glass volume hiding the internal bloom.
for i in range(8):
    angle=i*math.pi/4
    for tier,(radius,y,height,length) in enumerate(((5,-13,3,4),(7,-10,2,6),(9,-8,3,8))):
        name=f'shell{i}_{tier}';parts[name]=('bell',(math.sin(angle)*radius,y,math.cos(angle)*radius),angle)
        box(name,-length/2,0,-1.5,length,height,3)
    name=f'rim{i}';parts[name]=('rim',(math.sin(angle)*10,-5,math.cos(angle)*10),angle)
    box(name,-4,0,-1,8,3,2)
for x,width,depth in ((-6,2,8),(-4,8,12),(4,2,8)):
    box('bell',x,-14,-depth/2,width,1,depth)
box('core',-1,-1,-1,2,2,2)
for x,y,z in ((-3,-1,-1),(1,-1,-1),(-1,-3,-1),(-1,1,-1),(-1,-1,-3),(-1,-1,1)):
    box('core',x,y,z,2,2,2)
for i in range(6):
    # Offset the six spokes so opposing ribbons do not overlap in front/side views.
    angle=i*math.pi/3+math.pi/12;length=4
    for joint in range(6):
        name=f'ribbon{i}_{joint}'
        parent='body' if joint==0 else f'ribbon{i}_{joint-1}'
        pivot=(math.sin(angle)*6,-2,math.cos(angle)*6) if joint==0 else (0,length,0)
        parts[name]=(parent,pivot,angle if joint==0 else 0)
        height=6 if joint==5 and i%2==0 else length
        box(name,-(2 if joint<4 else 1)/2,0,-.5,2 if joint<4 else 1,height,1)
u=v=row=0
for b in boxes:
    width=2*(b['w']+b['d']);height=b['h']+b['d']
    if u+width>256:u=0;v+=row+1;row=0
    b['u']=u;b['v']=v;u+=width+1;row=max(row,height)
assert v+row<=256
code='''package com.nhat.tidal_terror.entities.veilglow;

// Generated by tools/create_veilglow_model.py; native UV export remains authoritative.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class VeilglowModel extends EntityModel<VeilglowEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"veilglow"),"main");
    private final ModelPart root,body,bell,rim,core;
    private final ModelPart[][] ribbons=new ModelPart[6][6];
    public VeilglowModel(ModelPart root) {
        this.root=root;body=root.getChild("body");bell=body.getChild("bell");rim=body.getChild("rim");core=body.getChild("core");
        for(int i=0;i<6;i++) { ModelPart parent=body;
            for(int j=0;j<6;j++){ribbons[i][j]=parent.getChild("ribbon"+i+"_"+j);parent=ribbons[i][j];}
        }
    }
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
'''
def f(n):return f'{n:.5f}F'
for name,(parent,pivot,angle) in parts.items():
    builder='CubeListBuilder.create()'
    for b in [b for b in boxes if b['part']==name]:
        builder+=f".texOffs({int(b['u'])},{int(b['v'])}).addBox({','.join(f(b[k]) for k in ('x','y','z','w','h','d'))})"
    # Bell/core cubes use their parent's coordinate frame; rebase around their pivots.
    if name in ('bell','core'):
        builder='CubeListBuilder.create()'
        for b in [b for b in boxes if b['part']==name]:
            xyz=[b[k]-(pivot[i] if name=='bell' else 0) for i,k in enumerate(('x','y','z'))]
            builder+=f".texOffs({int(b['u'])},{int(b['v'])}).addBox({','.join(f(n) for n in (*xyz,b['w'],b['h'],b['d']))})"
    offset=list(pivot)
    if parent in ('bell','rim'):offset=[pivot[i]-parts[parent][1][i] for i in range(3)]
    code+=f'        PartDefinition {name}={parent}.addOrReplaceChild("{name}",{builder},PartPose.offsetAndRotation({",".join(f(n) for n in (*offset,0,angle,0))}));\n'
code+='''        return LayerDefinition.create(mesh,256,256);
    }
    public void animatePose(float age,float speed,boolean water) {
        root.getAllParts().forEach(ModelPart::resetPose);
        float phase=age*(water?0.09F:0.22F);
        float pulse=Mth.sin(phase);
        bell.xScale=bell.zScale=1+0.045F*pulse;
        bell.yScale=1-0.07F*pulse;
        rim.xScale=rim.zScale=1+0.045F*pulse;
        core.xScale=core.yScale=core.zScale=1+0.035F*pulse;
        float amplitude=0.055F+Mth.clamp(speed*3,0,0.09F);
        for(int i=0;i<6;i++)for(int j=0;j<6;j++) {
            ribbons[i][j].xRot=0.045F+Mth.sin(phase-j*0.55F+i*0.7F)*amplitude;
            ribbons[i][j].zRot=Mth.cos(phase-j*0.45F+i)*0.035F;
        }
    }
    public void animateBehavior(float age,VeilglowEntity.Behavior state) {
        if(state==VeilglowEntity.Behavior.PULSE||state==VeilglowEntity.Behavior.FLEE){
            float squeeze=(Mth.sin(age*(state==VeilglowEntity.Behavior.FLEE?.36F:.25F))+1)*.5F;
            bell.xScale=bell.zScale=rim.xScale=rim.zScale=1-.10F*squeeze;
            bell.yScale=1-.18F*squeeze;core.xScale=core.yScale=core.zScale=1+.08F*squeeze;
            for(int i=0;i<6;i++)ribbons[i][0].xRot+=.12F*squeeze;
        }
    }
    @Override public void setupAnim(VeilglowEntity jelly,float swing,float amount,float age,float yaw,float pitch) {
        animatePose(age,(float)jelly.getDeltaMovement().length(),jelly.isInWater());
        animateBehavior(age,jelly.getBehavior());
    }
    @Override public void renderToBuffer(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a) {
        // Opaque interior first; the renderer draws the translucent bell afterward.
        core.render(pose,out,light,overlay,r,g,b,a);rim.render(pose,out,light,overlay,r,g,b,a);
        for(var ribbon:ribbons)ribbon[0].render(pose,out,light,overlay,r,g,b,a);
    }
    public void renderBell(PoseStack pose,VertexConsumer out,int light,int overlay) {bell.render(pose,out,light,overlay,1,1,1,1);}
    public void renderAll(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a) {root.render(pose,out,light,overlay,r,g,b,a);}
}
'''
p=ROOT/'src/main/java/com/nhat/tidal_terror/entities/veilglow/VeilglowModel.java';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(code)
work=ROOT/'build/veilglow-art';work.mkdir(parents=True,exist_ok=True)
(work/'box-layout.json').write_text(json.dumps(boxes,indent=2))
print('Generated',len(boxes),'cubes; 6 ribbon chains; atlas height',v+row)
