"""Generate Shardback's native cuboids, pivots and non-overlapping box UVs."""
from pathlib import Path
import math,json
ROOT=Path(__file__).resolve().parents[1]
parts={'body':('root',(0,16,0),(0,0,0))}
boxes=[]
def part(name,parent,pivot,rot=(0,0,0)):parts[name]=(parent,pivot,rot)
def box(name,x,y,z,w,h,d):boxes.append(dict(part=name,x=x,y=y,z=z,w=w,h=h,d=d))
# Broad, tapered carapace; shallow sand-colored belly underneath.
box('body',-6,-1,-6,12,4,12)
part('shell','body',(0,0,0))
box('shell',-8,-4,-5,16,3,10)
box('shell',-6,-5,-7,12,3,14)
box('shell',-5,-7,-5,10,2,10)
box('shell',-3,-9,-3,6,2,6)
box('shell',-2,-10,-1,4,1,3)
# Offset cobalt coral shards on the rear/right shoulder.
part('coral','body',(0,0,0))
for x,y,z,w,h,d in [(3,-9,0,3,3,4),(5,-7,2,3,3,3),(2,-10,3,3,2,3),(-5,-6,4,2,2,3),(-6,-5,-3,2,2,2)]:
    box('coral',x,y,z,w,h,d)
for side,s in [('left',1),('right',-1)]:
    for i in range(4):
        z=-4+i*3
        name=f'{side}leg{i}'
        angle=s*(.65-i*.43)
        part(name,'body',(s*6,1,z),(0,angle,s*.25))
        box(name,0 if s>0 else -6,-1,-1,6,2,2)
        lower=name+'lower';part(lower,name,(s*6,0,0),(0,0,s*-.55))
        box(lower,0 if s>0 else -2,0,-1,2,6,2)
        tip=name+'tip';part(tip,lower,(0,4,0))
        box(tip,-1,0,-1,2,2,2)
    eye=side+'eye';part(eye,'body',(s*3,-2,-8),(-.2,0,0))
    box(eye,-.5,-4,-1,1,4,1)
    pupil=side+'pupil';part(pupil,eye,(0,-4,0));box(pupil,-1,-1,-1.5,2,2,2)
    claw=side+'claw';part(claw,'body',(s*6,0,-5),(0,s*-.4,0))
    box(claw,-1,-1,-4,2,2,4)
    palm=side+'palm';part(palm,claw,(s*2,-1,-4),(0,s*-.2,0))
    size=5 if s>0 else 3
    box(palm,-size/2,-size/2,-size,size,size,size)
    fixed=side+'fixed';part(fixed,palm,(s*size/3,-.8,-size))
    box(fixed,-1,-1,-3,2,2,3);box(fixed,-1,-1,-4,1,2,1)
    finger=side+'finger';part(finger,palm,(-s*size/3,1.2,-size),(0,-s*.3,0))
    box(finger,-1,-1,-3,2,2,3);box(finger,0,-1,-4,1,2,1)
u=v=row=0
for b in boxes:
    width=2*(b['w']+b['d']);height=b['h']+b['d']
    if u+width>256:u=0;v+=row+1;row=0
    b['u']=u;b['v']=v;u+=width+1;row=max(row,height)
assert v+row<=256
def f(n):return f'{n:.5f}F'
code='''package com.nhat.tidal_terror.entities.shardback;
// Generated by tools/create_shardback_model.py; native face export verifies UVs.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.*;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
public class ShardbackModel extends EntityModel<ShardbackEntity> {
 public static final ModelLayerLocation LAYER=new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"shardback"),"main");
 private final ModelPart root,body;
 private final ModelPart[][] legs=new ModelPart[2][4];
 private final ModelPart[] fingers=new ModelPart[2];
 public ShardbackModel(ModelPart root){
  this.root=root;body=root.getChild("body");
  for(int s=0;s<2;s++){String side=s==0?"left":"right";
   for(int i=0;i<4;i++)legs[s][i]=body.getChild(side+"leg"+i);
   fingers[s]=body.getChild(side+"claw").getChild(side+"palm").getChild(side+"finger");
  }
 }
 public static LayerDefinition createBodyLayer(){
  MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
'''
for name,(parent,pivot,rot) in parts.items():
    builder='CubeListBuilder.create()'
    for b in [b for b in boxes if b['part']==name]:
        builder+=f".texOffs({int(b['u'])},{int(b['v'])}).addBox({','.join(f(b[k]) for k in ('x','y','z','w','h','d'))})"
    code+=f'  PartDefinition {name}={parent}.addOrReplaceChild("{name}",{builder},PartPose.offsetAndRotation({",".join(f(n) for n in (*pivot,*rot))}));\n'
code+='''  return LayerDefinition.create(mesh,256,256);
 }
 public void animatePose(float age,float speed,boolean water){
  root.getAllParts().forEach(ModelPart::resetPose);
  float move=Mth.clamp(speed*8,0,1);float phase=age*.14F;
  body.y+=Mth.sin(phase)*.08F;
  for(int s=0;s<2;s++)for(int i=0;i<4;i++){
   float step=Mth.sin(phase*2+i*Mth.PI+s*Mth.PI);
   legs[s][i].yRot+=step*.3F*move;
   legs[s][i].zRot+=(s==0?1:-1)*Math.max(0,Mth.cos(phase*2+i*Mth.PI+s*Mth.PI))*.24F*move;
  }
  fingers[0].yRot+=Mth.sin(phase*.7F)*.08F;
  fingers[1].yRot-=Mth.sin(phase*.7F+.8F)*.08F;
 }
 public void animateBehavior(float age,ShardbackEntity.Behavior state){
  for(int s=0;s<2;s++){
   String side=s==0?"left":"right";var claw=body.getChild(side+"claw");
   if(state==ShardbackEntity.Behavior.FORAGE){
    claw.xRot+=.2F+Mth.sin(age*.28F+s*Mth.PI)*.1F;
    fingers[s].yRot+=(s==0?1:-1)*Mth.sin(age*.4F)*.18F;
   }else if(state==ShardbackEntity.Behavior.THREATEN){
    claw.xRot-=.6F;fingers[s].yRot+=(s==0?-1:1)*.4F;
   }else if(state==ShardbackEntity.Behavior.SHELTER){
    body.y+=s==0?.5F:0;claw.xRot+=.15F;
    for(int i=0;i<4;i++)legs[s][i].zRot+=(s==0?1:-1)*.12F;
   }
  }
 }
 @Override public void setupAnim(ShardbackEntity crab,float swing,float amount,float age,float yaw,float pitch){
  animatePose(age,(float)crab.getDeltaMovement().horizontalDistance(),crab.isInWater());
  animateBehavior(age,crab.getBehavior());
 }
 @Override public void renderToBuffer(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a){root.render(pose,out,light,overlay,r,g,b,a);}
 public void renderAll(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a){renderToBuffer(pose,out,light,overlay,r,g,b,a);}
}
'''
out=ROOT/'common-1201/src/main/java/com/nhat/tidal_terror/entities/shardback/ShardbackModel.java'
out.parent.mkdir(parents=True,exist_ok=True);out.write_text(code)
work=ROOT/'build/shardback-art';work.mkdir(parents=True,exist_ok=True)
(work/'box-layout.json').write_text(json.dumps(boxes,indent=2))
print('SHARDBACK_GEOMETRY',len(boxes),'cuboids, eight articulated legs, asymmetric claws, atlas height',v+row)
