"""Generate the equipment's native cuboid geometry with unique, packed UV islands.

The approved orthographic guides shapes; EquipmentModelCheck exports the actual bake.
Material names in part paths drive the exact-face texture assembly.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'src/main/java/com/nhat/tidal_terror/client'
OUT.mkdir(parents=True, exist_ok=True)
SIZE = 256


class Builder:
    def __init__(self):
        self.x = self.y = self.row = 0
        self.lines = []
        self.index = 0

    def cube(self, parent, material, x, y, z, w, h, d):
        # Reserve complete native box UV footprints, including one-pixel gutters.
        width, height = int(2 * (w + d)), int(h + d)
        if self.x + width + 1 > SIZE:
            self.x = 0
            self.y += self.row + 1
            self.row = 0
        assert self.y + height < SIZE
        name = f'{material}_{self.index}'
        self.index += 1
        coords = ','.join(f'{v:.2f}F' for v in (x, y, z, w, h, d))
        # Slight distinct inflation separates intentionally layered shell faces.
        inflation = (self.index + 1) * .001
        self.lines.append(f'        {parent}.addOrReplaceChild("{name}", CubeListBuilder.create().texOffs({self.x},{self.y}).addBox({coords}, new CubeDeformation({inflation:.3f}F)), PartPose.ZERO);')
        self.x += width + 1
        self.row = max(self.row, height)


armor = Builder()
# Helmet: broad stepped carapace cap, open face, ivory side supports.
armor.lines.append('        if (slot == EquipmentSlot.HEAD) {')
for box in [(-5,-8,-5,10,2,10),(-4,-10,-4,8,2,8),(-3,-11,-3,6,1,6),(-5,-6,2,10,6,3)]:
    armor.cube('head','violet',*box)
for side in (-1,1):
    armor.cube('head','ivory', -5 if side < 0 else 4,-6,-4,1,6,6)
    armor.cube('head','violet', -5 if side < 0 else 4,-7,-5,1,3,7)
armor.cube('head','cobalt',3,-10,0,2,3,3)
armor.cube('head','cobalt',4,-8,2,2,3,3)
armor.lines.append('        }')
# Chest and back are broad shell sections, not fish scales.
armor.lines.append('        if (slot == EquipmentSlot.CHEST) {')
for z in (-4,2):
    armor.cube('body','ivory',-4,1,z,8,10,2)
    armor.cube('body','violet',-4,2,z-1 if z<0 else z+1,8,7,2)
    armor.cube('body','violet',-3,9,z-1 if z<0 else z+1,6,1,2)
for side in (-1,1):
    armor.cube('body','ivory',-5 if side<0 else 4,1,-2,1,10,4)
    arm = 'rightArm' if side<0 else 'leftArm'
    x = -4 if side<0 else -2
    armor.cube(arm,'ivory',x,-2,-3,6,3,6)
    armor.cube(arm,'violet',x,-3,-3,6,2,6)
    armor.cube(arm,'violet',x+1,-4,-2,4,1,4)
    armor.cube(arm,'ivory',x+1,5,-3,4,3,6)
    armor.cube(arm,'violet',x+1,5,-4,4,2,2)
    armor.cube(arm,'slate',x+1,8,-2,4,1,4)
armor.cube('leftArm','violet',-2,-3,-4,6,3,1)
armor.cube('leftArm','cobalt',1,-5,-2,2,3,3)
armor.cube('leftArm','cobalt',2,-3,1,2,2,3)
armor.cube('body','cobalt',-3,1,5,2,3,2)
armor.cube('body','cobalt',-2,4,5,2,3,2)
armor.lines.append('        }')
# Leggings: ivory belt and segmented thigh protection, slate joint gaps.
armor.lines.append('        if (slot == EquipmentSlot.LEGS) {')
armor.cube('body','ivory',-4,10,-3,8,2,6)
for leg in ('leftLeg','rightLeg'):
    armor.cube(leg,'ivory',-2.5,0,-3,5,5,6)
    armor.cube(leg,'violet',-2.5,1,-4,5,3,2)
    armor.cube(leg,'violet',-2.5,1,2,5,3,2)
    armor.cube(leg,'slate',-2.5,5,-2.5,5,1,5)
armor.lines.append('        }')
# Boots: sturdy ivory segments with violet outer panels and slate toes.
armor.lines.append('        if (slot == EquipmentSlot.FEET) {')
for leg in ('leftLeg','rightLeg'):
    armor.cube(leg,'ivory',-2.5,6,-3,5,5,6)
    armor.cube(leg,'violet',-2.5,7,-4,5,3,2)
    armor.cube(leg,'slate',-2.5,10,-3,5,1,6)
    armor.cube(leg,'ivory',-2.5,11,-4,5,2,7)
    armor.cube(leg,'slate',-1.5,11,-5,3,2,1)
armor.lines.append('        }')

(OUT/'ReefArmorModel.java').write_text('''package com.nhat.tidal_terror.client;
// Generated by tools/create_reef_equipment_models.py; native bake is the UV source of truth.
import com.nhat.tidal_terror.TidalTerror;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;

public final class ReefArmorModel extends HumanoidModel<LivingEntity> {
    public ReefArmorModel(ModelPart root) { super(root); }
    public static ModelLayerLocation layer(EquipmentSlot slot) {
        return new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID, "reef_armor"), slot.getName());
    }
    public static LayerDefinition createLayer(EquipmentSlot slot) {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.ZERO);
        root.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.ZERO);
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.ZERO);
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create(), PartPose.offset(-5,2,0));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create(), PartPose.offset(5,2,0));
        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create(), PartPose.offset(-1.9F,12,0));
        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create(), PartPose.offset(1.9F,12,0));
'''+'\n'.join(armor.lines)+'''
        return LayerDefinition.create(mesh, 256, 256);
    }
}
''', encoding='utf-8')

spear = Builder()
spear.cube('root','coral',-.5,-12,-.5,1,36,1)
for y in (-13,-10,0,2,18,22):
    spear.cube('root','hide',-1,y,-1,2,1,2)
spear.cube('root','hide',-1.5,-14,-1,3,2,2)
# Stepwise triangular tooth with small serrated edges; flat face, narrow side profile.
for x,y,w,h in [(-2,-18,4,4),(-1.5,-21,3,3),(-1,-24,2,3),(-.5,-26,1,2)]:
    spear.cube('root','tooth',x,y,-.5,w,h,1)
for y,w in [(-17,5),(-19,4),(-22,3)]:
    spear.cube('root','tooth',-w/2,y,-.5,w,1,1)
(OUT/'ReefSpearModel.java').write_text('''package com.nhat.tidal_terror.client;
// Generated by tools/create_reef_equipment_models.py.
import com.nhat.tidal_terror.TidalTerror;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;

public final class ReefSpearModel {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"reef_spear"), "main");
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
'''+'\n'.join(spear.lines)+'''
        return LayerDefinition.create(mesh,256,256);
    }
    private ReefSpearModel() {}
}
''', encoding='utf-8')
print(f'Generated {armor.index} armor cubes and {spear.index} spear cubes with packed 256x256 UVs')
