"""Rebuild the ray's Java geometry and an explicit non-overlapping box UV layout.
Artwork is assembled from native baked faces by ray_art.py, never guessed UVs.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'src/main/java/com/nhat/tidal_terror/entities/cathedral_ray/CathedralRayModel.java'
boxes=[]
def box(part,x,y,z,w,h,d):
    boxes.append(dict(part=part,x=x,y=y,z=z,w=w,h=h,d=d))
box('body',-4,-3,-18,8,5,29)
box('body',-3,-4,-15,6,1,23)
box('body',-3,-2,11,6,3,5)
box('body',-2,-1,16,4,2,4)
for side in ('left','right'):
    sign=1 if side=='left' else -1
    # Contiguous 2-texel ribs give the stepped diamond silhouette of the concept.
    for i in range(17):
        edge=4+2*i
        front=round(-15+i*.75)
        back=round(18-i*1.2)
        depth=max(3,back-front)
        group=min(i//6,2)
        part=f'{side}{group}'
        x=edge if sign>0 else -edge-2
        box(part,x,-1,front,2,2,depth)
    x=3 if sign>0 else -5
    box(side+'horn',x,-3,-23,2,3,6)
    box(side+'horn',x,-4,-25,2,2,2)
for i,(w,h,d) in enumerate(((3,2,6),(2,2,5),(2,1,4),(1,1,3))):
    box('tail'+str(i),-w/2,-h/2,20+sum((6,5,4,3)[:i]),w,h,d)

# Shelf pack each standard Minecraft unfolded cube, allocating fresh UVs to every cube.
u=v=row=0
for b in boxes:
    width=2*(b['w']+b['d']); height=b['h']+b['d']
    if u+width>512: u=0;v+=row+1;row=0
    b['u']=u;b['v']=v;u+=width+1;row=max(row,height)
assert v+row<=512

parts={'body':('root',(0,22,0))}
for side,sign in (('left',1),('right',-1)):
    for i in range(3): parts[side+str(i)]=('body' if i==0 else side+str(i-1),(sign*(4+12*i),0,0))
    parts[side+'horn']=('body',(sign*4,-2,-19))
for i in range(4): parts['tail'+str(i)]=('body' if i==0 else 'tail'+str(i-1),(0,0,20+sum((6,5,4,3)[:i])))
code='''package com.nhat.tidal_terror.entities.cathedral_ray;

// Geometry and independent UV allocation generated by tools/create_ray_model.py.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class CathedralRayModel extends EntityModel<CathedralRayEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID, "cathedral_ray"), "main");
    private final ModelPart root, body;
    private final ModelPart[] left = new ModelPart[3], right = new ModelPart[3], tail = new ModelPart[4];
    public CathedralRayModel(ModelPart root) {
        this.root = root; body = root.getChild("body");
        ModelPart l = body, r = body, t = body;
        for (int i=0;i<3;i++) { left[i]=l.getChild("left"+i); right[i]=r.getChild("right"+i); l=left[i]; r=right[i]; }
        for (int i=0;i<4;i++) { tail[i]=t.getChild("tail"+i); t=tail[i]; }
    }
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
'''
def f(n):return f'{float(n):.1f}F'
for name,(parent,pivot) in parts.items():
    offset=tuple(pivot[j]-(parts[parent][1][j] if parent not in ('root','body') else 0) for j in range(3))
    # Body's global vertical offset is separate from its model-local coordinates.
    builder='CubeListBuilder.create()'
    for b in [b for b in boxes if b['part']==name]:
        xyz=(b['x']-(pivot[0] if name!='body' else 0),b['y']-(pivot[1] if name!='body' else 0),b['z']-(pivot[2] if name!='body' else 0))
        builder+=f"\n                .texOffs({b['u']},{b['v']}).addBox({','.join(f(n) for n in (*xyz,b['w'],b['h'],b['d']))})"
    code+=f'        PartDefinition {name} = {parent}.addOrReplaceChild("{name}", {builder}, PartPose.offset({",".join(f(n) for n in offset)}));\n'
code+='''        return LayerDefinition.create(mesh, 512, 512);
    }
    public void animatePose(float age, float speed, float pitch, boolean water) {
        root.getAllParts().forEach(ModelPart::resetPose);
        float phase=age*(water?0.12F:0.45F);
        float amplitude=water?0.08F+Mth.clamp(speed*3,0,1)*0.16F:0.3F;
        for(int i=0;i<3;i++) {
            float stroke=Mth.sin(phase-i*0.6F)*amplitude;
            left[i].zRot=stroke; right[i].zRot=-stroke;
        }
        for(int i=0;i<4;i++) tail[i].yRot=Mth.sin(phase-i*0.5F)*0.08F;
        body.xRot=pitch*Mth.DEG_TO_RAD;
    }
    @Override public void setupAnim(CathedralRayEntity ray,float limbSwing,float limbAmount,float age,float yaw,float pitch) {
        animatePose(age,(float)ray.getDeltaMovement().length(),Mth.lerp(age-ray.tickCount,ray.xRotO,ray.getXRot()),ray.isInWater());
    }
    @Override public void renderToBuffer(PoseStack pose,VertexConsumer consumer,int light,int overlay,float r,float g,float b,float a) {
        root.render(pose,consumer,light,overlay,r,g,b,a);
    }
}
'''
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(code)
(ROOT/'build/ray-art').mkdir(parents=True,exist_ok=True)
(ROOT/'build/ray-art/box-layout.json').write_text(json.dumps(boxes,indent=2))
print('Generated',len(boxes),'cubes; atlas height',v+row)
