package com.nhat.tidal_terror.entities.shardback;
// Generated by tools/create_shardback_model.py; native face export verifies UVs.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.*;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
public class ShardbackModel extends EntityModel<ShardbackEntity> {
 public static final ModelLayerLocation LAYER=new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"shardback"),"main");
 private final ModelPart root,body;
 private final ModelPart[][] legs=new ModelPart[2][4];
 private final ModelPart[] fingers=new ModelPart[2];
 public ShardbackModel(ModelPart root){
  this.root=root;body=root.getChild("body");
  for(int s=0;s<2;s++){String side=s==0?"left":"right";
   for(int i=0;i<4;i++)legs[s][i]=body.getChild(side+"leg"+i);
   fingers[s]=body.getChild(side+"claw").getChild(side+"palm").getChild(side+"finger");
  }
 }
 public static LayerDefinition createBodyLayer(){
  MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
  PartDefinition body=root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.00000F,-1.00000F,-6.00000F,12.00000F,4.00000F,12.00000F),PartPose.offsetAndRotation(0.00000F,16.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition shell=body.addOrReplaceChild("shell",CubeListBuilder.create().texOffs(49,0).addBox(-8.00000F,-4.00000F,-5.00000F,16.00000F,3.00000F,10.00000F).texOffs(102,0).addBox(-6.00000F,-5.00000F,-7.00000F,12.00000F,3.00000F,14.00000F).texOffs(155,0).addBox(-5.00000F,-7.00000F,-5.00000F,10.00000F,2.00000F,10.00000F).texOffs(196,0).addBox(-3.00000F,-9.00000F,-3.00000F,6.00000F,2.00000F,6.00000F).texOffs(221,0).addBox(-2.00000F,-10.00000F,-1.00000F,4.00000F,1.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition coral=body.addOrReplaceChild("coral",CubeListBuilder.create().texOffs(236,0).addBox(3.00000F,-9.00000F,0.00000F,3.00000F,3.00000F,4.00000F).texOffs(0,18).addBox(5.00000F,-7.00000F,2.00000F,3.00000F,3.00000F,3.00000F).texOffs(13,18).addBox(2.00000F,-10.00000F,3.00000F,3.00000F,2.00000F,3.00000F).texOffs(26,18).addBox(-5.00000F,-6.00000F,4.00000F,2.00000F,2.00000F,3.00000F).texOffs(37,18).addBox(-6.00000F,-5.00000F,-3.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftleg0=body.addOrReplaceChild("leftleg0",CubeListBuilder.create().texOffs(46,18).addBox(0.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,1.00000F,-4.00000F,0.00000F,0.65000F,0.25000F));
  PartDefinition leftleg0lower=leftleg0.addOrReplaceChild("leftleg0lower",CubeListBuilder.create().texOffs(63,18).addBox(0.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,-0.55000F));
  PartDefinition leftleg0tip=leftleg0lower.addOrReplaceChild("leftleg0tip",CubeListBuilder.create().texOffs(72,18).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftleg1=body.addOrReplaceChild("leftleg1",CubeListBuilder.create().texOffs(81,18).addBox(0.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,1.00000F,-1.00000F,0.00000F,0.22000F,0.25000F));
  PartDefinition leftleg1lower=leftleg1.addOrReplaceChild("leftleg1lower",CubeListBuilder.create().texOffs(98,18).addBox(0.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,-0.55000F));
  PartDefinition leftleg1tip=leftleg1lower.addOrReplaceChild("leftleg1tip",CubeListBuilder.create().texOffs(107,18).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftleg2=body.addOrReplaceChild("leftleg2",CubeListBuilder.create().texOffs(116,18).addBox(0.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,1.00000F,2.00000F,0.00000F,-0.21000F,0.25000F));
  PartDefinition leftleg2lower=leftleg2.addOrReplaceChild("leftleg2lower",CubeListBuilder.create().texOffs(133,18).addBox(0.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,-0.55000F));
  PartDefinition leftleg2tip=leftleg2lower.addOrReplaceChild("leftleg2tip",CubeListBuilder.create().texOffs(142,18).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftleg3=body.addOrReplaceChild("leftleg3",CubeListBuilder.create().texOffs(151,18).addBox(0.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,1.00000F,5.00000F,0.00000F,-0.64000F,0.25000F));
  PartDefinition leftleg3lower=leftleg3.addOrReplaceChild("leftleg3lower",CubeListBuilder.create().texOffs(168,18).addBox(0.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,-0.55000F));
  PartDefinition leftleg3tip=leftleg3lower.addOrReplaceChild("leftleg3tip",CubeListBuilder.create().texOffs(177,18).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition lefteye=body.addOrReplaceChild("lefteye",CubeListBuilder.create().texOffs(186,18).addBox(-0.50000F,-4.00000F,-1.00000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(3.00000F,-2.00000F,-8.00000F,-0.20000F,0.00000F,0.00000F));
  PartDefinition leftpupil=lefteye.addOrReplaceChild("leftpupil",CubeListBuilder.create().texOffs(191,18).addBox(-1.00000F,-1.00000F,-1.50000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,-4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftclaw=body.addOrReplaceChild("leftclaw",CubeListBuilder.create().texOffs(200,18).addBox(-1.00000F,-1.00000F,-4.00000F,2.00000F,2.00000F,4.00000F),PartPose.offsetAndRotation(6.00000F,0.00000F,-5.00000F,0.00000F,-0.40000F,0.00000F));
  PartDefinition leftpalm=leftclaw.addOrReplaceChild("leftpalm",CubeListBuilder.create().texOffs(213,18).addBox(-2.50000F,-2.50000F,-5.00000F,5.00000F,5.00000F,5.00000F),PartPose.offsetAndRotation(2.00000F,-1.00000F,-4.00000F,0.00000F,-0.20000F,0.00000F));
  PartDefinition leftfixed=leftpalm.addOrReplaceChild("leftfixed",CubeListBuilder.create().texOffs(234,18).addBox(-1.00000F,-1.00000F,-3.00000F,2.00000F,2.00000F,3.00000F).texOffs(245,18).addBox(-1.00000F,-1.00000F,-4.00000F,1.00000F,2.00000F,1.00000F),PartPose.offsetAndRotation(1.66667F,-0.80000F,-5.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition leftfinger=leftpalm.addOrReplaceChild("leftfinger",CubeListBuilder.create().texOffs(0,29).addBox(-1.00000F,-1.00000F,-3.00000F,2.00000F,2.00000F,3.00000F).texOffs(11,29).addBox(0.00000F,-1.00000F,-4.00000F,1.00000F,2.00000F,1.00000F),PartPose.offsetAndRotation(-1.66667F,1.20000F,-5.00000F,0.00000F,-0.30000F,0.00000F));
  PartDefinition rightleg0=body.addOrReplaceChild("rightleg0",CubeListBuilder.create().texOffs(16,29).addBox(-6.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,1.00000F,-4.00000F,0.00000F,-0.65000F,-0.25000F));
  PartDefinition rightleg0lower=rightleg0.addOrReplaceChild("rightleg0lower",CubeListBuilder.create().texOffs(33,29).addBox(-2.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.55000F));
  PartDefinition rightleg0tip=rightleg0lower.addOrReplaceChild("rightleg0tip",CubeListBuilder.create().texOffs(42,29).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition rightleg1=body.addOrReplaceChild("rightleg1",CubeListBuilder.create().texOffs(51,29).addBox(-6.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,1.00000F,-1.00000F,0.00000F,-0.22000F,-0.25000F));
  PartDefinition rightleg1lower=rightleg1.addOrReplaceChild("rightleg1lower",CubeListBuilder.create().texOffs(68,29).addBox(-2.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.55000F));
  PartDefinition rightleg1tip=rightleg1lower.addOrReplaceChild("rightleg1tip",CubeListBuilder.create().texOffs(77,29).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition rightleg2=body.addOrReplaceChild("rightleg2",CubeListBuilder.create().texOffs(86,29).addBox(-6.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,1.00000F,2.00000F,0.00000F,0.21000F,-0.25000F));
  PartDefinition rightleg2lower=rightleg2.addOrReplaceChild("rightleg2lower",CubeListBuilder.create().texOffs(103,29).addBox(-2.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.55000F));
  PartDefinition rightleg2tip=rightleg2lower.addOrReplaceChild("rightleg2tip",CubeListBuilder.create().texOffs(112,29).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition rightleg3=body.addOrReplaceChild("rightleg3",CubeListBuilder.create().texOffs(121,29).addBox(-6.00000F,-1.00000F,-1.00000F,6.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,1.00000F,5.00000F,0.00000F,0.64000F,-0.25000F));
  PartDefinition rightleg3lower=rightleg3.addOrReplaceChild("rightleg3lower",CubeListBuilder.create().texOffs(138,29).addBox(-2.00000F,0.00000F,-1.00000F,2.00000F,6.00000F,2.00000F),PartPose.offsetAndRotation(-6.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.55000F));
  PartDefinition rightleg3tip=rightleg3lower.addOrReplaceChild("rightleg3tip",CubeListBuilder.create().texOffs(147,29).addBox(-1.00000F,0.00000F,-1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition righteye=body.addOrReplaceChild("righteye",CubeListBuilder.create().texOffs(156,29).addBox(-0.50000F,-4.00000F,-1.00000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(-3.00000F,-2.00000F,-8.00000F,-0.20000F,0.00000F,0.00000F));
  PartDefinition rightpupil=righteye.addOrReplaceChild("rightpupil",CubeListBuilder.create().texOffs(161,29).addBox(-1.00000F,-1.00000F,-1.50000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,-4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition rightclaw=body.addOrReplaceChild("rightclaw",CubeListBuilder.create().texOffs(170,29).addBox(-1.00000F,-1.00000F,-4.00000F,2.00000F,2.00000F,4.00000F),PartPose.offsetAndRotation(-6.00000F,0.00000F,-5.00000F,0.00000F,0.40000F,0.00000F));
  PartDefinition rightpalm=rightclaw.addOrReplaceChild("rightpalm",CubeListBuilder.create().texOffs(183,29).addBox(-1.50000F,-1.50000F,-3.00000F,3.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-2.00000F,-1.00000F,-4.00000F,0.00000F,0.20000F,0.00000F));
  PartDefinition rightfixed=rightpalm.addOrReplaceChild("rightfixed",CubeListBuilder.create().texOffs(196,29).addBox(-1.00000F,-1.00000F,-3.00000F,2.00000F,2.00000F,3.00000F).texOffs(207,29).addBox(-1.00000F,-1.00000F,-4.00000F,1.00000F,2.00000F,1.00000F),PartPose.offsetAndRotation(-1.00000F,-0.80000F,-3.00000F,0.00000F,0.00000F,0.00000F));
  PartDefinition rightfinger=rightpalm.addOrReplaceChild("rightfinger",CubeListBuilder.create().texOffs(212,29).addBox(-1.00000F,-1.00000F,-3.00000F,2.00000F,2.00000F,3.00000F).texOffs(223,29).addBox(0.00000F,-1.00000F,-4.00000F,1.00000F,2.00000F,1.00000F),PartPose.offsetAndRotation(1.00000F,1.20000F,-3.00000F,0.00000F,0.30000F,0.00000F));
  return LayerDefinition.create(mesh,256,256);
 }
 public void animatePose(float age,float speed,boolean water){
  root.getAllParts().forEach(ModelPart::resetPose);
  float move=Mth.clamp(speed*8,0,1);float phase=age*.14F;
  body.y+=Mth.sin(phase)*.08F;
  for(int s=0;s<2;s++)for(int i=0;i<4;i++){
   float step=Mth.sin(phase*2+i*Mth.PI+s*Mth.PI);
   legs[s][i].yRot+=step*.3F*move;
   legs[s][i].zRot+=(s==0?1:-1)*Math.max(0,Mth.cos(phase*2+i*Mth.PI+s*Mth.PI))*.24F*move;
  }
  fingers[0].yRot+=Mth.sin(phase*.7F)*.08F;
  fingers[1].yRot-=Mth.sin(phase*.7F+.8F)*.08F;
 }
 public void animateBehavior(float age,ShardbackEntity.Behavior state){
  for(int s=0;s<2;s++){
   String side=s==0?"left":"right";var claw=body.getChild(side+"claw");
   if(state==ShardbackEntity.Behavior.FORAGE){
    claw.xRot+=.2F+Mth.sin(age*.28F+s*Mth.PI)*.1F;
    fingers[s].yRot+=(s==0?1:-1)*Mth.sin(age*.4F)*.18F;
   }else if(state==ShardbackEntity.Behavior.THREATEN){
    claw.xRot-=.6F;fingers[s].yRot+=(s==0?-1:1)*.4F;
   }else if(state==ShardbackEntity.Behavior.SHELTER){
    body.y+=s==0?.5F:0;claw.xRot+=.15F;
    for(int i=0;i<4;i++)legs[s][i].zRot+=(s==0?1:-1)*.12F;
   }
  }
 }
 @Override public void setupAnim(ShardbackEntity crab,float swing,float amount,float age,float yaw,float pitch){
  animatePose(age,(float)crab.getDeltaMovement().horizontalDistance(),crab.isInWater());
  animateBehavior(age,crab.getBehavior());
 }
 @Override public void renderToBuffer(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a){root.render(pose,out,light,overlay,r,g,b,a);}
 public void renderAll(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a){renderToBuffer(pose,out,light,overlay,r,g,b,a);}
}
