package com.nhat.tidal_terror.entities.cathedral_ray;

// Geometry and independent UV allocation generated by tools/create_ray_model.py.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class CathedralRayModel extends EntityModel<CathedralRayEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID, "cathedral_ray"), "main");
    private final ModelPart root, body;
    private final ModelPart[] left = new ModelPart[3], right = new ModelPart[3], tail = new ModelPart[4];
    public CathedralRayModel(ModelPart root) {
        this.root = root; body = root.getChild("body");
        ModelPart l = body, r = body, t = body;
        for (int i=0;i<3;i++) { left[i]=l.getChild("left"+i); right[i]=r.getChild("right"+i); l=left[i]; r=right[i]; }
        for (int i=0;i<4;i++) { tail[i]=t.getChild("tail"+i); t=tail[i]; }
    }
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0,0).addBox(-4.0F,-3.0F,-18.0F,8.0F,5.0F,29.0F)
                .texOffs(75,0).addBox(-3.0F,-4.0F,-15.0F,6.0F,1.0F,23.0F)
                .texOffs(134,0).addBox(-3.0F,-2.0F,11.0F,6.0F,3.0F,5.0F)
                .texOffs(157,0).addBox(-2.0F,-1.0F,16.0F,4.0F,2.0F,4.0F), PartPose.offset(0.0F,22.0F,0.0F));
        PartDefinition left0 = body.addOrReplaceChild("left0", CubeListBuilder.create()
                .texOffs(174,0).addBox(0.0F,-1.0F,-15.0F,2.0F,2.0F,33.0F)
                .texOffs(245,0).addBox(2.0F,-1.0F,-14.0F,2.0F,2.0F,31.0F)
                .texOffs(312,0).addBox(4.0F,-1.0F,-14.0F,2.0F,2.0F,30.0F)
                .texOffs(377,0).addBox(6.0F,-1.0F,-13.0F,2.0F,2.0F,27.0F)
                .texOffs(436,0).addBox(8.0F,-1.0F,-12.0F,2.0F,2.0F,25.0F)
                .texOffs(0,36).addBox(10.0F,-1.0F,-11.0F,2.0F,2.0F,23.0F), PartPose.offset(4.0F,0.0F,0.0F));
        PartDefinition left1 = left0.addOrReplaceChild("left1", CubeListBuilder.create()
                .texOffs(51,36).addBox(0.0F,-1.0F,-10.0F,2.0F,2.0F,21.0F)
                .texOffs(98,36).addBox(2.0F,-1.0F,-10.0F,2.0F,2.0F,20.0F)
                .texOffs(143,36).addBox(4.0F,-1.0F,-9.0F,2.0F,2.0F,17.0F)
                .texOffs(182,36).addBox(6.0F,-1.0F,-8.0F,2.0F,2.0F,15.0F)
                .texOffs(217,36).addBox(8.0F,-1.0F,-8.0F,2.0F,2.0F,14.0F)
                .texOffs(250,36).addBox(10.0F,-1.0F,-7.0F,2.0F,2.0F,12.0F), PartPose.offset(12.0F,0.0F,0.0F));
        PartDefinition left2 = left1.addOrReplaceChild("left2", CubeListBuilder.create()
                .texOffs(279,36).addBox(0.0F,-1.0F,-6.0F,2.0F,2.0F,10.0F)
                .texOffs(304,36).addBox(2.0F,-1.0F,-5.0F,2.0F,2.0F,7.0F)
                .texOffs(323,36).addBox(4.0F,-1.0F,-4.0F,2.0F,2.0F,5.0F)
                .texOffs(338,36).addBox(6.0F,-1.0F,-4.0F,2.0F,2.0F,4.0F)
                .texOffs(351,36).addBox(8.0F,-1.0F,-3.0F,2.0F,2.0F,3.0F), PartPose.offset(12.0F,0.0F,0.0F));
        PartDefinition lefthorn = body.addOrReplaceChild("lefthorn", CubeListBuilder.create()
                .texOffs(362,36).addBox(-1.0F,-1.0F,-4.0F,2.0F,3.0F,6.0F)
                .texOffs(379,36).addBox(-1.0F,-2.0F,-6.0F,2.0F,2.0F,2.0F), PartPose.offset(4.0F,-2.0F,-19.0F));
        PartDefinition right0 = body.addOrReplaceChild("right0", CubeListBuilder.create()
                .texOffs(388,36).addBox(-2.0F,-1.0F,-15.0F,2.0F,2.0F,33.0F)
                .texOffs(0,72).addBox(-4.0F,-1.0F,-14.0F,2.0F,2.0F,31.0F)
                .texOffs(67,72).addBox(-6.0F,-1.0F,-14.0F,2.0F,2.0F,30.0F)
                .texOffs(132,72).addBox(-8.0F,-1.0F,-13.0F,2.0F,2.0F,27.0F)
                .texOffs(191,72).addBox(-10.0F,-1.0F,-12.0F,2.0F,2.0F,25.0F)
                .texOffs(246,72).addBox(-12.0F,-1.0F,-11.0F,2.0F,2.0F,23.0F), PartPose.offset(-4.0F,0.0F,0.0F));
        PartDefinition right1 = right0.addOrReplaceChild("right1", CubeListBuilder.create()
                .texOffs(297,72).addBox(-2.0F,-1.0F,-10.0F,2.0F,2.0F,21.0F)
                .texOffs(344,72).addBox(-4.0F,-1.0F,-10.0F,2.0F,2.0F,20.0F)
                .texOffs(389,72).addBox(-6.0F,-1.0F,-9.0F,2.0F,2.0F,17.0F)
                .texOffs(428,72).addBox(-8.0F,-1.0F,-8.0F,2.0F,2.0F,15.0F)
                .texOffs(463,72).addBox(-10.0F,-1.0F,-8.0F,2.0F,2.0F,14.0F)
                .texOffs(0,106).addBox(-12.0F,-1.0F,-7.0F,2.0F,2.0F,12.0F), PartPose.offset(-12.0F,0.0F,0.0F));
        PartDefinition right2 = right1.addOrReplaceChild("right2", CubeListBuilder.create()
                .texOffs(29,106).addBox(-2.0F,-1.0F,-6.0F,2.0F,2.0F,10.0F)
                .texOffs(54,106).addBox(-4.0F,-1.0F,-5.0F,2.0F,2.0F,7.0F)
                .texOffs(73,106).addBox(-6.0F,-1.0F,-4.0F,2.0F,2.0F,5.0F)
                .texOffs(88,106).addBox(-8.0F,-1.0F,-4.0F,2.0F,2.0F,4.0F)
                .texOffs(101,106).addBox(-10.0F,-1.0F,-3.0F,2.0F,2.0F,3.0F), PartPose.offset(-12.0F,0.0F,0.0F));
        PartDefinition righthorn = body.addOrReplaceChild("righthorn", CubeListBuilder.create()
                .texOffs(112,106).addBox(-1.0F,-1.0F,-4.0F,2.0F,3.0F,6.0F)
                .texOffs(129,106).addBox(-1.0F,-2.0F,-6.0F,2.0F,2.0F,2.0F), PartPose.offset(-4.0F,-2.0F,-19.0F));
        PartDefinition tail0 = body.addOrReplaceChild("tail0", CubeListBuilder.create()
                .texOffs(138,106).addBox(-1.5F,-1.0F,0.0F,3.0F,2.0F,6.0F), PartPose.offset(0.0F,0.0F,20.0F));
        PartDefinition tail1 = tail0.addOrReplaceChild("tail1", CubeListBuilder.create()
                .texOffs(157,106).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,5.0F), PartPose.offset(0.0F,0.0F,6.0F));
        PartDefinition tail2 = tail1.addOrReplaceChild("tail2", CubeListBuilder.create()
                .texOffs(172,106).addBox(-1.0F,-0.5F,0.0F,2.0F,1.0F,4.0F), PartPose.offset(0.0F,0.0F,5.0F));
        PartDefinition tail3 = tail2.addOrReplaceChild("tail3", CubeListBuilder.create()
                .texOffs(185,106).addBox(-0.5F,-0.5F,0.0F,1.0F,1.0F,3.0F), PartPose.offset(0.0F,0.0F,4.0F));
        return LayerDefinition.create(mesh, 512, 512);
    }
    public void animatePose(float age, float speed, float pitch, boolean water) {
        root.getAllParts().forEach(ModelPart::resetPose);
        float phase=age*(water?0.12F:0.45F);
        float amplitude=water?0.08F+Mth.clamp(speed*3,0,1)*0.16F:0.3F;
        for(int i=0;i<3;i++) {
            float stroke=Mth.sin(phase-i*0.6F)*amplitude;
            left[i].zRot=stroke; right[i].zRot=-stroke;
        }
        for(int i=0;i<4;i++) tail[i].yRot=Mth.sin(phase-i*0.5F)*0.08F;
        body.xRot=pitch*Mth.DEG_TO_RAD;
    }
    @Override public void setupAnim(CathedralRayEntity ray,float limbSwing,float limbAmount,float age,float yaw,float pitch) {
        animatePose(age,(float)ray.getDeltaMovement().length(),Mth.lerp(age-ray.tickCount,ray.xRotO,ray.getXRot()),ray.isInWater());
    }
    @Override public void renderToBuffer(PoseStack pose,VertexConsumer consumer,int light,int overlay,float r,float g,float b,float a) {
        root.render(pose,consumer,light,overlay,r,g,b,a);
    }
}
