package com.nhat.tidal_terror.entities.veilglow;

// Generated by tools/create_veilglow_model.py; native UV export remains authoritative.
import com.nhat.tidal_terror.TidalTerror;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class VeilglowModel extends EntityModel<VeilglowEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(TidalTerror.MODID,"veilglow"),"main");
    private final ModelPart root,body,bell,rim,core;
    private final ModelPart[][] ribbons=new ModelPart[6][6];
    public VeilglowModel(ModelPart root) {
        this.root=root;body=root.getChild("body");bell=body.getChild("bell");rim=body.getChild("rim");core=body.getChild("core");
        for(int i=0;i<6;i++) { ModelPart parent=body;
            for(int j=0;j<6;j++){ribbons[i][j]=parent.getChild("ribbon"+i+"_"+j);parent=ribbons[i][j];}
        }
    }
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh=new MeshDefinition();PartDefinition root=mesh.getRoot();
        PartDefinition body=root.addOrReplaceChild("body",CubeListBuilder.create(),PartPose.offsetAndRotation(0.00000F,0.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition bell=body.addOrReplaceChild("bell",CubeListBuilder.create().texOffs(122,14).addBox(-6.00000F,-9.00000F,-4.00000F,2.00000F,1.00000F,8.00000F).texOffs(143,14).addBox(-4.00000F,-9.00000F,-6.00000F,8.00000F,1.00000F,12.00000F).texOffs(184,14).addBox(4.00000F,-9.00000F,-4.00000F,2.00000F,1.00000F,8.00000F),PartPose.offsetAndRotation(0.00000F,-5.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition rim=body.addOrReplaceChild("rim",CubeListBuilder.create(),PartPose.offsetAndRotation(0.00000F,-5.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition core=body.addOrReplaceChild("core",CubeListBuilder.create().texOffs(205,14).addBox(-1.00000F,-1.00000F,-1.00000F,2.00000F,2.00000F,2.00000F).texOffs(214,14).addBox(-3.00000F,-1.00000F,-1.00000F,2.00000F,2.00000F,2.00000F).texOffs(223,14).addBox(1.00000F,-1.00000F,-1.00000F,2.00000F,2.00000F,2.00000F).texOffs(232,14).addBox(-1.00000F,-3.00000F,-1.00000F,2.00000F,2.00000F,2.00000F).texOffs(241,14).addBox(-1.00000F,1.00000F,-1.00000F,2.00000F,2.00000F,2.00000F).texOffs(0,28).addBox(-1.00000F,-1.00000F,-3.00000F,2.00000F,2.00000F,2.00000F).texOffs(9,28).addBox(-1.00000F,-1.00000F,1.00000F,2.00000F,2.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,-8.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition shell0_0=bell.addOrReplaceChild("shell0_0",CubeListBuilder.create().texOffs(0,0).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-8.00000F,5.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition shell0_1=bell.addOrReplaceChild("shell0_1",CubeListBuilder.create().texOffs(15,0).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-5.00000F,7.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition shell0_2=bell.addOrReplaceChild("shell0_2",CubeListBuilder.create().texOffs(34,0).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-3.00000F,9.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition rim0=rim.addOrReplaceChild("rim0",CubeListBuilder.create().texOffs(57,0).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,0.00000F,10.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition shell1_0=bell.addOrReplaceChild("shell1_0",CubeListBuilder.create().texOffs(78,0).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(3.53553F,-8.00000F,3.53553F,0.00000F,0.78540F,0.00000F));
        PartDefinition shell1_1=bell.addOrReplaceChild("shell1_1",CubeListBuilder.create().texOffs(93,0).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(4.94975F,-5.00000F,4.94975F,0.00000F,0.78540F,0.00000F));
        PartDefinition shell1_2=bell.addOrReplaceChild("shell1_2",CubeListBuilder.create().texOffs(112,0).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(6.36396F,-3.00000F,6.36396F,0.00000F,0.78540F,0.00000F));
        PartDefinition rim1=rim.addOrReplaceChild("rim1",CubeListBuilder.create().texOffs(135,0).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(7.07107F,0.00000F,7.07107F,0.00000F,0.78540F,0.00000F));
        PartDefinition shell2_0=bell.addOrReplaceChild("shell2_0",CubeListBuilder.create().texOffs(156,0).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(5.00000F,-8.00000F,0.00000F,0.00000F,1.57080F,0.00000F));
        PartDefinition shell2_1=bell.addOrReplaceChild("shell2_1",CubeListBuilder.create().texOffs(171,0).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(7.00000F,-5.00000F,0.00000F,0.00000F,1.57080F,0.00000F));
        PartDefinition shell2_2=bell.addOrReplaceChild("shell2_2",CubeListBuilder.create().texOffs(190,0).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(9.00000F,-3.00000F,0.00000F,0.00000F,1.57080F,0.00000F));
        PartDefinition rim2=rim.addOrReplaceChild("rim2",CubeListBuilder.create().texOffs(213,0).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(10.00000F,0.00000F,0.00000F,0.00000F,1.57080F,0.00000F));
        PartDefinition shell3_0=bell.addOrReplaceChild("shell3_0",CubeListBuilder.create().texOffs(234,0).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(3.53553F,-8.00000F,-3.53553F,0.00000F,2.35619F,0.00000F));
        PartDefinition shell3_1=bell.addOrReplaceChild("shell3_1",CubeListBuilder.create().texOffs(0,7).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(4.94975F,-5.00000F,-4.94975F,0.00000F,2.35619F,0.00000F));
        PartDefinition shell3_2=bell.addOrReplaceChild("shell3_2",CubeListBuilder.create().texOffs(19,7).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(6.36396F,-3.00000F,-6.36396F,0.00000F,2.35619F,0.00000F));
        PartDefinition rim3=rim.addOrReplaceChild("rim3",CubeListBuilder.create().texOffs(42,7).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(7.07107F,0.00000F,-7.07107F,0.00000F,2.35619F,0.00000F));
        PartDefinition shell4_0=bell.addOrReplaceChild("shell4_0",CubeListBuilder.create().texOffs(63,7).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-8.00000F,-5.00000F,0.00000F,3.14159F,0.00000F));
        PartDefinition shell4_1=bell.addOrReplaceChild("shell4_1",CubeListBuilder.create().texOffs(78,7).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-5.00000F,-7.00000F,0.00000F,3.14159F,0.00000F));
        PartDefinition shell4_2=bell.addOrReplaceChild("shell4_2",CubeListBuilder.create().texOffs(97,7).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(0.00000F,-3.00000F,-9.00000F,0.00000F,3.14159F,0.00000F));
        PartDefinition rim4=rim.addOrReplaceChild("rim4",CubeListBuilder.create().texOffs(120,7).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(0.00000F,0.00000F,-10.00000F,0.00000F,3.14159F,0.00000F));
        PartDefinition shell5_0=bell.addOrReplaceChild("shell5_0",CubeListBuilder.create().texOffs(141,7).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-3.53553F,-8.00000F,-3.53553F,0.00000F,3.92699F,0.00000F));
        PartDefinition shell5_1=bell.addOrReplaceChild("shell5_1",CubeListBuilder.create().texOffs(156,7).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(-4.94975F,-5.00000F,-4.94975F,0.00000F,3.92699F,0.00000F));
        PartDefinition shell5_2=bell.addOrReplaceChild("shell5_2",CubeListBuilder.create().texOffs(175,7).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-6.36396F,-3.00000F,-6.36396F,0.00000F,3.92699F,0.00000F));
        PartDefinition rim5=rim.addOrReplaceChild("rim5",CubeListBuilder.create().texOffs(198,7).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(-7.07107F,0.00000F,-7.07107F,0.00000F,3.92699F,0.00000F));
        PartDefinition shell6_0=bell.addOrReplaceChild("shell6_0",CubeListBuilder.create().texOffs(219,7).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-5.00000F,-8.00000F,-0.00000F,0.00000F,4.71239F,0.00000F));
        PartDefinition shell6_1=bell.addOrReplaceChild("shell6_1",CubeListBuilder.create().texOffs(234,7).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(-7.00000F,-5.00000F,-0.00000F,0.00000F,4.71239F,0.00000F));
        PartDefinition shell6_2=bell.addOrReplaceChild("shell6_2",CubeListBuilder.create().texOffs(0,14).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-9.00000F,-3.00000F,-0.00000F,0.00000F,4.71239F,0.00000F));
        PartDefinition rim6=rim.addOrReplaceChild("rim6",CubeListBuilder.create().texOffs(23,14).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(-10.00000F,0.00000F,-0.00000F,0.00000F,4.71239F,0.00000F));
        PartDefinition shell7_0=bell.addOrReplaceChild("shell7_0",CubeListBuilder.create().texOffs(44,14).addBox(-2.00000F,0.00000F,-1.50000F,4.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-3.53553F,-8.00000F,3.53553F,0.00000F,5.49779F,0.00000F));
        PartDefinition shell7_1=bell.addOrReplaceChild("shell7_1",CubeListBuilder.create().texOffs(59,14).addBox(-3.00000F,0.00000F,-1.50000F,6.00000F,2.00000F,3.00000F),PartPose.offsetAndRotation(-4.94975F,-5.00000F,4.94975F,0.00000F,5.49779F,0.00000F));
        PartDefinition shell7_2=bell.addOrReplaceChild("shell7_2",CubeListBuilder.create().texOffs(78,14).addBox(-4.00000F,0.00000F,-1.50000F,8.00000F,3.00000F,3.00000F),PartPose.offsetAndRotation(-6.36396F,-3.00000F,6.36396F,0.00000F,5.49779F,0.00000F));
        PartDefinition rim7=rim.addOrReplaceChild("rim7",CubeListBuilder.create().texOffs(101,14).addBox(-4.00000F,0.00000F,-1.00000F,8.00000F,3.00000F,2.00000F),PartPose.offsetAndRotation(-7.07107F,0.00000F,7.07107F,0.00000F,5.49779F,0.00000F));
        PartDefinition ribbon0_0=body.addOrReplaceChild("ribbon0_0",CubeListBuilder.create().texOffs(18,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(1.55291F,-2.00000F,5.79555F,0.00000F,0.26180F,0.00000F));
        PartDefinition ribbon0_1=ribbon0_0.addOrReplaceChild("ribbon0_1",CubeListBuilder.create().texOffs(25,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon0_2=ribbon0_1.addOrReplaceChild("ribbon0_2",CubeListBuilder.create().texOffs(32,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon0_3=ribbon0_2.addOrReplaceChild("ribbon0_3",CubeListBuilder.create().texOffs(39,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon0_4=ribbon0_3.addOrReplaceChild("ribbon0_4",CubeListBuilder.create().texOffs(46,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon0_5=ribbon0_4.addOrReplaceChild("ribbon0_5",CubeListBuilder.create().texOffs(51,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,6.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon1_0=body.addOrReplaceChild("ribbon1_0",CubeListBuilder.create().texOffs(56,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(5.79555F,-2.00000F,1.55291F,0.00000F,1.30900F,0.00000F));
        PartDefinition ribbon1_1=ribbon1_0.addOrReplaceChild("ribbon1_1",CubeListBuilder.create().texOffs(63,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon1_2=ribbon1_1.addOrReplaceChild("ribbon1_2",CubeListBuilder.create().texOffs(70,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon1_3=ribbon1_2.addOrReplaceChild("ribbon1_3",CubeListBuilder.create().texOffs(77,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon1_4=ribbon1_3.addOrReplaceChild("ribbon1_4",CubeListBuilder.create().texOffs(84,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon1_5=ribbon1_4.addOrReplaceChild("ribbon1_5",CubeListBuilder.create().texOffs(89,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon2_0=body.addOrReplaceChild("ribbon2_0",CubeListBuilder.create().texOffs(94,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(4.24264F,-2.00000F,-4.24264F,0.00000F,2.35619F,0.00000F));
        PartDefinition ribbon2_1=ribbon2_0.addOrReplaceChild("ribbon2_1",CubeListBuilder.create().texOffs(101,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon2_2=ribbon2_1.addOrReplaceChild("ribbon2_2",CubeListBuilder.create().texOffs(108,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon2_3=ribbon2_2.addOrReplaceChild("ribbon2_3",CubeListBuilder.create().texOffs(115,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon2_4=ribbon2_3.addOrReplaceChild("ribbon2_4",CubeListBuilder.create().texOffs(122,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon2_5=ribbon2_4.addOrReplaceChild("ribbon2_5",CubeListBuilder.create().texOffs(127,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,6.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon3_0=body.addOrReplaceChild("ribbon3_0",CubeListBuilder.create().texOffs(132,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(-1.55291F,-2.00000F,-5.79555F,0.00000F,3.40339F,0.00000F));
        PartDefinition ribbon3_1=ribbon3_0.addOrReplaceChild("ribbon3_1",CubeListBuilder.create().texOffs(139,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon3_2=ribbon3_1.addOrReplaceChild("ribbon3_2",CubeListBuilder.create().texOffs(146,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon3_3=ribbon3_2.addOrReplaceChild("ribbon3_3",CubeListBuilder.create().texOffs(153,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon3_4=ribbon3_3.addOrReplaceChild("ribbon3_4",CubeListBuilder.create().texOffs(160,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon3_5=ribbon3_4.addOrReplaceChild("ribbon3_5",CubeListBuilder.create().texOffs(165,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon4_0=body.addOrReplaceChild("ribbon4_0",CubeListBuilder.create().texOffs(170,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(-5.79555F,-2.00000F,-1.55291F,0.00000F,4.45059F,0.00000F));
        PartDefinition ribbon4_1=ribbon4_0.addOrReplaceChild("ribbon4_1",CubeListBuilder.create().texOffs(177,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon4_2=ribbon4_1.addOrReplaceChild("ribbon4_2",CubeListBuilder.create().texOffs(184,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon4_3=ribbon4_2.addOrReplaceChild("ribbon4_3",CubeListBuilder.create().texOffs(191,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon4_4=ribbon4_3.addOrReplaceChild("ribbon4_4",CubeListBuilder.create().texOffs(198,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon4_5=ribbon4_4.addOrReplaceChild("ribbon4_5",CubeListBuilder.create().texOffs(203,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,6.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon5_0=body.addOrReplaceChild("ribbon5_0",CubeListBuilder.create().texOffs(208,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(-4.24264F,-2.00000F,4.24264F,0.00000F,5.49779F,0.00000F));
        PartDefinition ribbon5_1=ribbon5_0.addOrReplaceChild("ribbon5_1",CubeListBuilder.create().texOffs(215,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon5_2=ribbon5_1.addOrReplaceChild("ribbon5_2",CubeListBuilder.create().texOffs(222,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon5_3=ribbon5_2.addOrReplaceChild("ribbon5_3",CubeListBuilder.create().texOffs(229,28).addBox(-1.00000F,0.00000F,-0.50000F,2.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon5_4=ribbon5_3.addOrReplaceChild("ribbon5_4",CubeListBuilder.create().texOffs(236,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        PartDefinition ribbon5_5=ribbon5_4.addOrReplaceChild("ribbon5_5",CubeListBuilder.create().texOffs(241,28).addBox(-0.50000F,0.00000F,-0.50000F,1.00000F,4.00000F,1.00000F),PartPose.offsetAndRotation(0.00000F,4.00000F,0.00000F,0.00000F,0.00000F,0.00000F));
        return LayerDefinition.create(mesh,256,256);
    }
    public void animatePose(float age,float speed,boolean water) {
        root.getAllParts().forEach(ModelPart::resetPose);
        float phase=age*(water?0.09F:0.22F);
        float pulse=Mth.sin(phase);
        bell.xScale=bell.zScale=1+0.045F*pulse;
        bell.yScale=1-0.07F*pulse;
        rim.xScale=rim.zScale=1+0.045F*pulse;
        core.xScale=core.yScale=core.zScale=1+0.035F*pulse;
        float amplitude=0.055F+Mth.clamp(speed*3,0,0.09F);
        for(int i=0;i<6;i++)for(int j=0;j<6;j++) {
            ribbons[i][j].xRot=0.045F+Mth.sin(phase-j*0.55F+i*0.7F)*amplitude;
            ribbons[i][j].zRot=Mth.cos(phase-j*0.45F+i)*0.035F;
        }
    }
    public void animateBehavior(float age,VeilglowEntity.Behavior state) {
        if(state==VeilglowEntity.Behavior.PULSE||state==VeilglowEntity.Behavior.FLEE){
            float squeeze=(Mth.sin(age*(state==VeilglowEntity.Behavior.FLEE?.36F:.25F))+1)*.5F;
            bell.xScale=bell.zScale=rim.xScale=rim.zScale=1-.10F*squeeze;
            bell.yScale=1-.18F*squeeze;core.xScale=core.yScale=core.zScale=1+.08F*squeeze;
            for(int i=0;i<6;i++)ribbons[i][0].xRot+=.12F*squeeze;
        }
    }
    @Override public void setupAnim(VeilglowEntity jelly,float swing,float amount,float age,float yaw,float pitch) {
        animatePose(age,(float)jelly.getDeltaMovement().length(),jelly.isInWater());
        animateBehavior(age,jelly.getBehavior());
    }
    @Override public void renderToBuffer(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a) {
        // Opaque interior first; the renderer draws the translucent bell afterward.
        core.render(pose,out,light,overlay,r,g,b,a);rim.render(pose,out,light,overlay,r,g,b,a);
        for(var ribbon:ribbons)ribbon[0].render(pose,out,light,overlay,r,g,b,a);
    }
    public void renderBell(PoseStack pose,VertexConsumer out,int light,int overlay) {bell.render(pose,out,light,overlay,1,1,1,1);}
    public void renderAll(PoseStack pose,VertexConsumer out,int light,int overlay,float r,float g,float b,float a) {root.render(pose,out,light,overlay,r,g,b,a);}
}
